### ISSUE TITLE
Super grub disk still stands out

### ISSUE THREAD

**Issue by slowpeek** [thias/glim#107]
[Jan 3, 2019](https://github.com/thias/glim/issues/25#issuecomment-451290827):

> .. this is the first ISO image that doesn't require a sub-directory inside "iso", as I plan to change all of them to be like this **soon**

Super grub disk is still the only distro without a subdir. What is the current development direction on the matter?

**Comment by thias** [comment]
Well, I had started it, as seen here: https://github.com/thias/glim/compare/master...glim2

**Comment by slowpeek** [comment]
Yeah, I vote for subdirs as well

**Comment by thias** [comment]
This should do it. Their beta and main iso have completely different naming, for some reason:
```
-for_each_sorted add_menu "$isopath"/super_grub2_disk_*.iso
+for_each_sorted add_menu "$isopath"/supergrubdisk/super*.iso
```
Can't test easily right away, but will push once tested.

**Comment by slowpeek** [comment]
How do you test btw? I have a 100G `glim.img` file with such partitions (gdisk output):

```
Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048            4095   1024.0 KiB  EF02  BIOS boot partition
   2            4096           86015   40.0 MiB    EF00  EFI system partition
   3           86016       209715166   100.0 GiB   8300  Linux filesystem
```

It has grub-pc and grub-efi installed (including shim). The image is attached to two virtual machines in virt-manager, bios one and efi one. 

So I `sudo losetup -f glim.img && sudo partprobe /dev/loop0 && udisksctl mount -b /dev/loop0p3` and keep it that way all the time, even when the virtual machines are running. Since grub never writes to the disk (aside for `grubenv`) nothing bad happens.

**Comment by thias** [comment]
Closing, as I finally made the change!

About testing, I actually use a very similar setup, but with a real USB stick, mounted on my laptop and used to boot in VMs from virt-manager using directly sda as an emulated SATA disk (for whatever reason it didn't used to work as USB when I initially tried, but that was a while ago). I have one regular VM and another EFI one too. I used to umount/mount the USB stick each time I booted the VM, because I had some fs corruption a while back, but more recently I've been keeping it mounted with no issues (as indeed nothing should be writing to the FAT filesystem from the VM).

When I finish my testing, I unplug my USB stick and always carry it around with me :smile:
