### ISSUE TITLE
Don't show 64-bit ISOs in menu if CPU is 32-bit

### ISSUE THREAD

**Issue by steve6375** [thias/glim#46]
Since grub2 knows the CPU architecture, you could add a test before each menuentry to check that the $arch is compatible?
e.g. currently if I boot to UEFI-32 or MBR-32, the menus lists all 64-bit ISOs.

**Comment by thias** [comment]
Closing this, since it was being done, but with the dynamic menus it's now much too difficult to keep doing. Most entries still properly display the arch in the menu, so it's easy to see which one to pick if you know you're on a 32bit computer. If you don't know it, well... you'll find out soon enough :laughing:
